-- 
-- LOG
--

CREATE DATABASE IF NOT EXISTS Syslog /*!40100 DEFAULT CHARACTER SET utf8 */;
USE Syslog;

DROP TABLE IF EXISTS SystemEvents;
CREATE TABLE SystemEvents (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ReceivedAt DATETIME NULL,
  SysLogTag VARCHAR(60),
  Severity VARCHAR(60) NULL,
  Message TEXT
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
