# Use fixed image to RabbitMQ
FROM rabbitmq:3.9.11-management-alpine

# Common labels
LABEL maintainer="Murilo Chianfa <github.com/murilochianfa>"
LABEL br.com.redstore.version="0.0.1-beta"
LABEL br.com.redstore.version.is-production="no"
LABEL br.com.redstore.release-date="2021-11-25"
LABEL vendor="Redstore"

# Queue port
EXPOSE 5672

# Web port
EXPOSE 15672

# installing curl
RUN apk update && apk add curl

# set reference for conf file
ADD rabbitmq.conf /etc/rabbitmq/

# default options
ADD definitions.json /etc/rabbitmq/

# set permissions
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf /etc/rabbitmq/definitions.json
