name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      working-directory: ./API/API
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Install dependencies to API
      working-directory: ./API/API
      run: composer install --prefer-dist --no-progress

    - name: Run test suite to API
      working-directory: ./API/API
      run: composer run-script test

    - name: Install dependencies to Web
      working-directory: ./Web/Frontend
      run: composer install --prefer-dist --no-progress

    - name: Run test suite to Web
      working-directory: ./Web/Frontend
      run: composer run-script test
